"""Add role fields to Moderator

Revision ID: c0511b416c54
Revises: 6dbdfc1f7491
Create Date: 2024-09-22 17:46:04.313354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0511b416c54'
down_revision: Union[str, None] = '6dbdfc1f7491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('moderator', sa.Column('is_user', sa.Boolean(), nullable=True))
    op.add_column('moderator', sa.Column('is_cashier', sa.Boolean(), nullable=True))
    op.add_column('moderator', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('moderator', 'is_admin')
    op.drop_column('moderator', 'is_cashier')
    op.drop_column('moderator', 'is_user')
    # ### end Alembic commands ###
